In [1]:
from pathlib import Path  

path_vocab = "vocab.txt" 
with Path(path_vocab).open() as f: 
    for idx, line in enumerate(f): 
        print(idx, '->', line.strip())

0 -> flight
1 -> airport
2 -> plane


In [2]:
import tensorflow as tf  

tf.enable_eager_execution() 

lookup_table = tf.contrib.lookup.index_table_from_file(path_vocab, num_oov_buckets=1) 

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [8]:
words = tf.constant(['flight', 'airport', 'plane', 'random'])  
# length of dictionary plus one for unknown words 
depth = 4
for word in words:  
    idx = lookup_table.lookup(word)
    one_hot_embedding = tf.one_hot(idx, depth)  # output: [3 x 3]
    print(one_hot_embedding)

tf.Tensor([1. 0. 0. 0.], shape=(4,), dtype=float32)
tf.Tensor([0. 1. 0. 0.], shape=(4,), dtype=float32)
tf.Tensor([0. 0. 1. 0.], shape=(4,), dtype=float32)
tf.Tensor([0. 0. 0. 1.], shape=(4,), dtype=float32)
